// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/auth/v1/service.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_auth_v1_service_proto protoreflect.FileDescriptor

const file_api_auth_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x19api/auth/v1/service.proto\x12\aauth.v1\x1a\x1aapi/auth/v1/messages.proto2\xca\x01\n" +
	"\vAuthService\x12A\n" +
	"\bRegister\x12\x18.auth.v1.RegisterRequest\x1a\x19.auth.v1.RegisterResponse\"\x00\x128\n" +
	"\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x16.auth.v1.LoginResponse\"\x00\x12>\n" +
	"\aRefresh\x12\x17.auth.v1.RefreshRequest\x1a\x18.auth.v1.RefreshResponse\"\x00B\x1aZ\x18proto/api/auth/v1;authv1b\x06proto3"

var file_api_auth_v1_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: auth.v1.RegisterRequest
	(*LoginRequest)(nil),     // 1: auth.v1.LoginRequest
	(*RefreshRequest)(nil),   // 2: auth.v1.RefreshRequest
	(*RegisterResponse)(nil), // 3: auth.v1.RegisterResponse
	(*LoginResponse)(nil),    // 4: auth.v1.LoginResponse
	(*RefreshResponse)(nil),  // 5: auth.v1.RefreshResponse
}
var file_api_auth_v1_service_proto_depIdxs = []int32{
	0, // 0: auth.v1.AuthService.Register:input_type -> auth.v1.RegisterRequest
	1, // 1: auth.v1.AuthService.Login:input_type -> auth.v1.LoginRequest
	2, // 2: auth.v1.AuthService.Refresh:input_type -> auth.v1.RefreshRequest
	3, // 3: auth.v1.AuthService.Register:output_type -> auth.v1.RegisterResponse
	4, // 4: auth.v1.AuthService.Login:output_type -> auth.v1.LoginResponse
	5, // 5: auth.v1.AuthService.Refresh:output_type -> auth.v1.RefreshResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_v1_service_proto_init() }
func file_api_auth_v1_service_proto_init() {
	if File_api_auth_v1_service_proto != nil {
		return
	}
	file_api_auth_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_service_proto_rawDesc), len(file_api_auth_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_v1_service_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_service_proto_depIdxs,
	}.Build()
	File_api_auth_v1_service_proto = out.File
	file_api_auth_v1_service_proto_goTypes = nil
	file_api_auth_v1_service_proto_depIdxs = nil
}
