// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/chat/v1/service.proto

package chatv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_chat_v1_service_proto protoreflect.FileDescriptor

const file_api_chat_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x19api/chat/v1/service.proto\x12\achat.v1\x1a\x1aapi/chat/v1/messages.proto2\xb5\x04\n" +
	"\vChatService\x12Y\n" +
	"\x10CreateDirectChat\x12 .chat.v1.CreateDirectChatRequest\x1a!.chat.v1.CreateDirectChatResponse\"\x00\x12>\n" +
	"\aGetChat\x12\x17.chat.v1.GetChatRequest\x1a\x18.chat.v1.GetChatResponse\"\x00\x12P\n" +
	"\rListUserChats\x12\x1d.chat.v1.ListUserChatsRequest\x1a\x1e.chat.v1.ListUserChatsResponse\"\x00\x12V\n" +
	"\x0fListChatMembers\x12\x1f.chat.v1.ListChatMembersRequest\x1a .chat.v1.ListChatMembersResponse\"\x00\x12J\n" +
	"\vSendMessage\x12\x1b.chat.v1.SendMessageRequest\x1a\x1c.chat.v1.SendMessageResponse\"\x00\x12M\n" +
	"\fListMessages\x12\x1c.chat.v1.ListMessagesRequest\x1a\x1d.chat.v1.ListMessagesResponse\"\x00\x12F\n" +
	"\x0eStreamMessages\x12\x1e.chat.v1.StreamMessagesRequest\x1a\x10.chat.v1.Message\"\x000\x01B\x1aZ\x18proto/api/chat/v1;chatv1b\x06proto3"

var file_api_chat_v1_service_proto_goTypes = []any{
	(*CreateDirectChatRequest)(nil),  // 0: chat.v1.CreateDirectChatRequest
	(*GetChatRequest)(nil),           // 1: chat.v1.GetChatRequest
	(*ListUserChatsRequest)(nil),     // 2: chat.v1.ListUserChatsRequest
	(*ListChatMembersRequest)(nil),   // 3: chat.v1.ListChatMembersRequest
	(*SendMessageRequest)(nil),       // 4: chat.v1.SendMessageRequest
	(*ListMessagesRequest)(nil),      // 5: chat.v1.ListMessagesRequest
	(*StreamMessagesRequest)(nil),    // 6: chat.v1.StreamMessagesRequest
	(*CreateDirectChatResponse)(nil), // 7: chat.v1.CreateDirectChatResponse
	(*GetChatResponse)(nil),          // 8: chat.v1.GetChatResponse
	(*ListUserChatsResponse)(nil),    // 9: chat.v1.ListUserChatsResponse
	(*ListChatMembersResponse)(nil),  // 10: chat.v1.ListChatMembersResponse
	(*SendMessageResponse)(nil),      // 11: chat.v1.SendMessageResponse
	(*ListMessagesResponse)(nil),     // 12: chat.v1.ListMessagesResponse
	(*Message)(nil),                  // 13: chat.v1.Message
}
var file_api_chat_v1_service_proto_depIdxs = []int32{
	0,  // 0: chat.v1.ChatService.CreateDirectChat:input_type -> chat.v1.CreateDirectChatRequest
	1,  // 1: chat.v1.ChatService.GetChat:input_type -> chat.v1.GetChatRequest
	2,  // 2: chat.v1.ChatService.ListUserChats:input_type -> chat.v1.ListUserChatsRequest
	3,  // 3: chat.v1.ChatService.ListChatMembers:input_type -> chat.v1.ListChatMembersRequest
	4,  // 4: chat.v1.ChatService.SendMessage:input_type -> chat.v1.SendMessageRequest
	5,  // 5: chat.v1.ChatService.ListMessages:input_type -> chat.v1.ListMessagesRequest
	6,  // 6: chat.v1.ChatService.StreamMessages:input_type -> chat.v1.StreamMessagesRequest
	7,  // 7: chat.v1.ChatService.CreateDirectChat:output_type -> chat.v1.CreateDirectChatResponse
	8,  // 8: chat.v1.ChatService.GetChat:output_type -> chat.v1.GetChatResponse
	9,  // 9: chat.v1.ChatService.ListUserChats:output_type -> chat.v1.ListUserChatsResponse
	10, // 10: chat.v1.ChatService.ListChatMembers:output_type -> chat.v1.ListChatMembersResponse
	11, // 11: chat.v1.ChatService.SendMessage:output_type -> chat.v1.SendMessageResponse
	12, // 12: chat.v1.ChatService.ListMessages:output_type -> chat.v1.ListMessagesResponse
	13, // 13: chat.v1.ChatService.StreamMessages:output_type -> chat.v1.Message
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_chat_v1_service_proto_init() }
func file_api_chat_v1_service_proto_init() {
	if File_api_chat_v1_service_proto != nil {
		return
	}
	file_api_chat_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_chat_v1_service_proto_rawDesc), len(file_api_chat_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_chat_v1_service_proto_goTypes,
		DependencyIndexes: file_api_chat_v1_service_proto_depIdxs,
	}.Build()
	File_api_chat_v1_service_proto = out.File
	file_api_chat_v1_service_proto_goTypes = nil
	file_api_chat_v1_service_proto_depIdxs = nil
}
