// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/users/v1/service.proto

package usersv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_users_v1_service_proto protoreflect.FileDescriptor

const file_api_users_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/users/v1/service.proto\x12\busers.v1\x1a\x1bapi/users/v1/messages.proto2\xa2\x03\n" +
	"\vUserService\x12H\n" +
	"\rCreateProfile\x12\x1e.users.v1.CreateProfileRequest\x1a\x15.users.v1.UserProfile\"\x00\x12H\n" +
	"\rUpdateProfile\x12\x1e.users.v1.UpdateProfileRequest\x1a\x15.users.v1.UserProfile\"\x00\x12J\n" +
	"\x0eGetProfileByID\x12\x1f.users.v1.GetProfileByIDRequest\x1a\x15.users.v1.UserProfile\"\x00\x12V\n" +
	"\x14GetProfileByNickname\x12%.users.v1.GetProfileByNicknameRequest\x1a\x15.users.v1.UserProfile\"\x00\x12[\n" +
	"\x10SearchByNickname\x12!.users.v1.SearchByNicknameRequest\x1a\".users.v1.SearchByNicknameResponse\"\x00B\x1cZ\x1aproto/api/users/v1;usersv1b\x06proto3"

var file_api_users_v1_service_proto_goTypes = []any{
	(*CreateProfileRequest)(nil),        // 0: users.v1.CreateProfileRequest
	(*UpdateProfileRequest)(nil),        // 1: users.v1.UpdateProfileRequest
	(*GetProfileByIDRequest)(nil),       // 2: users.v1.GetProfileByIDRequest
	(*GetProfileByNicknameRequest)(nil), // 3: users.v1.GetProfileByNicknameRequest
	(*SearchByNicknameRequest)(nil),     // 4: users.v1.SearchByNicknameRequest
	(*UserProfile)(nil),                 // 5: users.v1.UserProfile
	(*SearchByNicknameResponse)(nil),    // 6: users.v1.SearchByNicknameResponse
}
var file_api_users_v1_service_proto_depIdxs = []int32{
	0, // 0: users.v1.UserService.CreateProfile:input_type -> users.v1.CreateProfileRequest
	1, // 1: users.v1.UserService.UpdateProfile:input_type -> users.v1.UpdateProfileRequest
	2, // 2: users.v1.UserService.GetProfileByID:input_type -> users.v1.GetProfileByIDRequest
	3, // 3: users.v1.UserService.GetProfileByNickname:input_type -> users.v1.GetProfileByNicknameRequest
	4, // 4: users.v1.UserService.SearchByNickname:input_type -> users.v1.SearchByNicknameRequest
	5, // 5: users.v1.UserService.CreateProfile:output_type -> users.v1.UserProfile
	5, // 6: users.v1.UserService.UpdateProfile:output_type -> users.v1.UserProfile
	5, // 7: users.v1.UserService.GetProfileByID:output_type -> users.v1.UserProfile
	5, // 8: users.v1.UserService.GetProfileByNickname:output_type -> users.v1.UserProfile
	6, // 9: users.v1.UserService.SearchByNickname:output_type -> users.v1.SearchByNicknameResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_users_v1_service_proto_init() }
func file_api_users_v1_service_proto_init() {
	if File_api_users_v1_service_proto != nil {
		return
	}
	file_api_users_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_users_v1_service_proto_rawDesc), len(file_api_users_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_users_v1_service_proto_goTypes,
		DependencyIndexes: file_api_users_v1_service_proto_depIdxs,
	}.Build()
	File_api_users_v1_service_proto = out.File
	file_api_users_v1_service_proto_goTypes = nil
	file_api_users_v1_service_proto_depIdxs = nil
}
