// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/social/v1/service.proto

package socialv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_social_v1_service_proto protoreflect.FileDescriptor

const file_api_social_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/social/v1/service.proto\x12\tsocial.v1\x1a\x1capi/social/v1/messages.proto\x1a\x1bgoogle/protobuf/empty.proto2\xb1\x04\n" +
	"\rSocialService\x12`\n" +
	"\x11SendFriendRequest\x12#.social.v1.SendFriendRequestRequest\x1a$.social.v1.SendFriendRequestResponse\"\x00\x12Q\n" +
	"\fListRequests\x12\x1e.social.v1.ListRequestsRequest\x1a\x1f.social.v1.ListRequestsResponse\"\x00\x12f\n" +
	"\x13AcceptFriendRequest\x12%.social.v1.AcceptFriendRequestRequest\x1a&.social.v1.AcceptFriendRequestResponse\"\x00\x12i\n" +
	"\x14DeclineFriendRequest\x12&.social.v1.DeclineFriendRequestRequest\x1a'.social.v1.DeclineFriendRequestResponse\"\x00\x12H\n" +
	"\fRemoveFriend\x12\x1e.social.v1.RemoveFriendRequest\x1a\x16.google.protobuf.Empty\"\x00\x12N\n" +
	"\vListFriends\x12\x1d.social.v1.ListFriendsRequest\x1a\x1e.social.v1.ListFriendsResponse\"\x00B\x1eZ\x1cproto/api/social/v1;socialv1b\x06proto3"

var file_api_social_v1_service_proto_goTypes = []any{
	(*SendFriendRequestRequest)(nil),     // 0: social.v1.SendFriendRequestRequest
	(*ListRequestsRequest)(nil),          // 1: social.v1.ListRequestsRequest
	(*AcceptFriendRequestRequest)(nil),   // 2: social.v1.AcceptFriendRequestRequest
	(*DeclineFriendRequestRequest)(nil),  // 3: social.v1.DeclineFriendRequestRequest
	(*RemoveFriendRequest)(nil),          // 4: social.v1.RemoveFriendRequest
	(*ListFriendsRequest)(nil),           // 5: social.v1.ListFriendsRequest
	(*SendFriendRequestResponse)(nil),    // 6: social.v1.SendFriendRequestResponse
	(*ListRequestsResponse)(nil),         // 7: social.v1.ListRequestsResponse
	(*AcceptFriendRequestResponse)(nil),  // 8: social.v1.AcceptFriendRequestResponse
	(*DeclineFriendRequestResponse)(nil), // 9: social.v1.DeclineFriendRequestResponse
	(*emptypb.Empty)(nil),                // 10: google.protobuf.Empty
	(*ListFriendsResponse)(nil),          // 11: social.v1.ListFriendsResponse
}
var file_api_social_v1_service_proto_depIdxs = []int32{
	0,  // 0: social.v1.SocialService.SendFriendRequest:input_type -> social.v1.SendFriendRequestRequest
	1,  // 1: social.v1.SocialService.ListRequests:input_type -> social.v1.ListRequestsRequest
	2,  // 2: social.v1.SocialService.AcceptFriendRequest:input_type -> social.v1.AcceptFriendRequestRequest
	3,  // 3: social.v1.SocialService.DeclineFriendRequest:input_type -> social.v1.DeclineFriendRequestRequest
	4,  // 4: social.v1.SocialService.RemoveFriend:input_type -> social.v1.RemoveFriendRequest
	5,  // 5: social.v1.SocialService.ListFriends:input_type -> social.v1.ListFriendsRequest
	6,  // 6: social.v1.SocialService.SendFriendRequest:output_type -> social.v1.SendFriendRequestResponse
	7,  // 7: social.v1.SocialService.ListRequests:output_type -> social.v1.ListRequestsResponse
	8,  // 8: social.v1.SocialService.AcceptFriendRequest:output_type -> social.v1.AcceptFriendRequestResponse
	9,  // 9: social.v1.SocialService.DeclineFriendRequest:output_type -> social.v1.DeclineFriendRequestResponse
	10, // 10: social.v1.SocialService.RemoveFriend:output_type -> google.protobuf.Empty
	11, // 11: social.v1.SocialService.ListFriends:output_type -> social.v1.ListFriendsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_social_v1_service_proto_init() }
func file_api_social_v1_service_proto_init() {
	if File_api_social_v1_service_proto != nil {
		return
	}
	file_api_social_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_social_v1_service_proto_rawDesc), len(file_api_social_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_social_v1_service_proto_goTypes,
		DependencyIndexes: file_api_social_v1_service_proto_depIdxs,
	}.Build()
	File_api_social_v1_service_proto = out.File
	file_api_social_v1_service_proto_goTypes = nil
	file_api_social_v1_service_proto_depIdxs = nil
}
